on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  compile:
    name: Compile all keymaps
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix develop .#container --command fak compile_all
      - uses: EndBug/latest-tag@latest
      - uses: ncipollo/release-action@v1
        with:
          tag: latest
          artifacts: ".fak_cache/*.ihx"
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          makeLatest: true
